apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot-zlafou.git"
    targetRevision: main
    path: ./app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
